# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/BasicTypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/BasicTypes.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16proto/BasicTypes.proto\x1a\x0cnanopb.proto\",\n\tHederaKey\x12\x18\n\x07\x65\x64\x32\x35\x35\x31\x39\x18\x02 \x01(\x0c\x42\x05\x92?\x02\x08 H\x00\x42\x05\n\x03key\"!\n\rHederaShardID\x12\x10\n\x08shardNum\x18\x01 \x01(\x04\"3\n\rHederaRealmID\x12\x10\n\x08shardNum\x18\x01 \x01(\x04\x12\x10\n\x08realmNum\x18\x02 \x01(\x04\"I\n\x0fHederaAccountID\x12\x10\n\x08shardNum\x18\x01 \x01(\x04\x12\x10\n\x08realmNum\x18\x02 \x01(\x04\x12\x12\n\naccountNum\x18\x03 \x01(\x04\"E\n\rHederaTokenID\x12\x10\n\x08shardNum\x18\x01 \x01(\x04\x12\x10\n\x08realmNum\x18\x02 \x01(\x04\x12\x10\n\x08tokenNum\x18\x03 \x01(\x04\"1\n\x0fHederaTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x04\x12\r\n\x05nanos\x18\x02 \x01(\r\"!\n\x0eHederaDuration\x12\x0f\n\x07seconds\x18\x01 \x01(\x04\":\n\x13HederaTransactionID\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.HederaAccountIDb\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_HEDERAKEY = _descriptor.Descriptor(
  name='HederaKey',
  full_name='HederaKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ed25519', full_name='HederaKey.ed25519', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\010 '), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='key', full_name='HederaKey.key',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=40,
  serialized_end=84,
)


_HEDERASHARDID = _descriptor.Descriptor(
  name='HederaShardID',
  full_name='HederaShardID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shardNum', full_name='HederaShardID.shardNum', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=119,
)


_HEDERAREALMID = _descriptor.Descriptor(
  name='HederaRealmID',
  full_name='HederaRealmID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shardNum', full_name='HederaRealmID.shardNum', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='realmNum', full_name='HederaRealmID.realmNum', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=172,
)


_HEDERAACCOUNTID = _descriptor.Descriptor(
  name='HederaAccountID',
  full_name='HederaAccountID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shardNum', full_name='HederaAccountID.shardNum', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='realmNum', full_name='HederaAccountID.realmNum', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accountNum', full_name='HederaAccountID.accountNum', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=247,
)


_HEDERATOKENID = _descriptor.Descriptor(
  name='HederaTokenID',
  full_name='HederaTokenID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shardNum', full_name='HederaTokenID.shardNum', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='realmNum', full_name='HederaTokenID.realmNum', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenNum', full_name='HederaTokenID.tokenNum', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=318,
)


_HEDERATIMESTAMP = _descriptor.Descriptor(
  name='HederaTimestamp',
  full_name='HederaTimestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='HederaTimestamp.seconds', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nanos', full_name='HederaTimestamp.nanos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=369,
)


_HEDERADURATION = _descriptor.Descriptor(
  name='HederaDuration',
  full_name='HederaDuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='HederaDuration.seconds', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=404,
)


_HEDERATRANSACTIONID = _descriptor.Descriptor(
  name='HederaTransactionID',
  full_name='HederaTransactionID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountID', full_name='HederaTransactionID.accountID', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=464,
)

_HEDERAKEY.oneofs_by_name['key'].fields.append(
  _HEDERAKEY.fields_by_name['ed25519'])
_HEDERAKEY.fields_by_name['ed25519'].containing_oneof = _HEDERAKEY.oneofs_by_name['key']
_HEDERATRANSACTIONID.fields_by_name['accountID'].message_type = _HEDERAACCOUNTID
DESCRIPTOR.message_types_by_name['HederaKey'] = _HEDERAKEY
DESCRIPTOR.message_types_by_name['HederaShardID'] = _HEDERASHARDID
DESCRIPTOR.message_types_by_name['HederaRealmID'] = _HEDERAREALMID
DESCRIPTOR.message_types_by_name['HederaAccountID'] = _HEDERAACCOUNTID
DESCRIPTOR.message_types_by_name['HederaTokenID'] = _HEDERATOKENID
DESCRIPTOR.message_types_by_name['HederaTimestamp'] = _HEDERATIMESTAMP
DESCRIPTOR.message_types_by_name['HederaDuration'] = _HEDERADURATION
DESCRIPTOR.message_types_by_name['HederaTransactionID'] = _HEDERATRANSACTIONID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HederaKey = _reflection.GeneratedProtocolMessageType('HederaKey', (_message.Message,), dict(
  DESCRIPTOR = _HEDERAKEY,
  __module__ = 'proto.BasicTypes_pb2'
  # @@protoc_insertion_point(class_scope:HederaKey)
  ))
_sym_db.RegisterMessage(HederaKey)

HederaShardID = _reflection.GeneratedProtocolMessageType('HederaShardID', (_message.Message,), dict(
  DESCRIPTOR = _HEDERASHARDID,
  __module__ = 'proto.BasicTypes_pb2'
  # @@protoc_insertion_point(class_scope:HederaShardID)
  ))
_sym_db.RegisterMessage(HederaShardID)

HederaRealmID = _reflection.GeneratedProtocolMessageType('HederaRealmID', (_message.Message,), dict(
  DESCRIPTOR = _HEDERAREALMID,
  __module__ = 'proto.BasicTypes_pb2'
  # @@protoc_insertion_point(class_scope:HederaRealmID)
  ))
_sym_db.RegisterMessage(HederaRealmID)

HederaAccountID = _reflection.GeneratedProtocolMessageType('HederaAccountID', (_message.Message,), dict(
  DESCRIPTOR = _HEDERAACCOUNTID,
  __module__ = 'proto.BasicTypes_pb2'
  # @@protoc_insertion_point(class_scope:HederaAccountID)
  ))
_sym_db.RegisterMessage(HederaAccountID)

HederaTokenID = _reflection.GeneratedProtocolMessageType('HederaTokenID', (_message.Message,), dict(
  DESCRIPTOR = _HEDERATOKENID,
  __module__ = 'proto.BasicTypes_pb2'
  # @@protoc_insertion_point(class_scope:HederaTokenID)
  ))
_sym_db.RegisterMessage(HederaTokenID)

HederaTimestamp = _reflection.GeneratedProtocolMessageType('HederaTimestamp', (_message.Message,), dict(
  DESCRIPTOR = _HEDERATIMESTAMP,
  __module__ = 'proto.BasicTypes_pb2'
  # @@protoc_insertion_point(class_scope:HederaTimestamp)
  ))
_sym_db.RegisterMessage(HederaTimestamp)

HederaDuration = _reflection.GeneratedProtocolMessageType('HederaDuration', (_message.Message,), dict(
  DESCRIPTOR = _HEDERADURATION,
  __module__ = 'proto.BasicTypes_pb2'
  # @@protoc_insertion_point(class_scope:HederaDuration)
  ))
_sym_db.RegisterMessage(HederaDuration)

HederaTransactionID = _reflection.GeneratedProtocolMessageType('HederaTransactionID', (_message.Message,), dict(
  DESCRIPTOR = _HEDERATRANSACTIONID,
  __module__ = 'proto.BasicTypes_pb2'
  # @@protoc_insertion_point(class_scope:HederaTransactionID)
  ))
_sym_db.RegisterMessage(HederaTransactionID)


_HEDERAKEY.fields_by_name['ed25519']._options = None
# @@protoc_insertion_point(module_scope)
