/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Jun 30 15:04:31 2021. */

#include "BasicTypes.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HederaKey_fields[2] = {
    PB_ONEOF_FIELD(key,   2, BYTES   , ONEOF, STATIC  , FIRST, HederaKey, ed25519, ed25519, 0),
    PB_LAST_FIELD
};

const pb_field_t HederaShardID_fields[2] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, HederaShardID, shardNum, shardNum, 0),
    PB_LAST_FIELD
};

const pb_field_t HederaRealmID_fields[3] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, HederaRealmID, shardNum, shardNum, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, HederaRealmID, realmNum, shardNum, 0),
    PB_LAST_FIELD
};

const pb_field_t HederaAccountID_fields[4] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, HederaAccountID, shardNum, shardNum, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, HederaAccountID, realmNum, shardNum, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, HederaAccountID, accountNum, realmNum, 0),
    PB_LAST_FIELD
};

const pb_field_t HederaTimestamp_fields[3] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, HederaTimestamp, seconds, seconds, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, HederaTimestamp, nanos, seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t HederaDuration_fields[2] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, HederaDuration, seconds, seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t HederaTransactionID_fields[2] = {
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , FIRST, HederaTransactionID, accountID, accountID, &HederaAccountID_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(HederaTransactionID, accountID) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_HederaKey_HederaShardID_HederaRealmID_HederaAccountID_HederaTimestamp_HederaDuration_HederaTransactionID)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(HederaTransactionID, accountID) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_HederaKey_HederaShardID_HederaRealmID_HederaAccountID_HederaTimestamp_HederaDuration_HederaTransactionID)
#endif


/* @@protoc_insertion_point(eof) */
