/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "proto/BasicTypes.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HederaKey, HederaKey, AUTO)


PB_BIND(HederaShardID, HederaShardID, AUTO)


PB_BIND(HederaRealmID, HederaRealmID, AUTO)


PB_BIND(HederaAccountID, HederaAccountID, AUTO)


PB_BIND(HederaTimestamp, HederaTimestamp, AUTO)


PB_BIND(HederaDuration, HederaDuration, AUTO)


PB_BIND(HederaTransactionID, HederaTransactionID, AUTO)



