/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Wed Jun 30 15:04:31 2021. */

#ifndef PB_CRYPTOCREATETRANSACTIONBODY_PB_H_INCLUDED
#define PB_CRYPTOCREATETRANSACTIONBODY_PB_H_INCLUDED
#include <pb.h>

#include "BasicTypes.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HederaCryptoCreateTransactionBody {
    uint64_t initialBalance;
/* @@protoc_insertion_point(struct:HederaCryptoCreateTransactionBody) */
} HederaCryptoCreateTransactionBody;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HederaCryptoCreateTransactionBody_init_default {0}
#define HederaCryptoCreateTransactionBody_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define HederaCryptoCreateTransactionBody_initialBalance_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t HederaCryptoCreateTransactionBody_fields[2];

/* Maximum encoded size of messages (where known) */
#define HederaCryptoCreateTransactionBody_size   11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CRYPTOCREATETRANSACTIONBODY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
