/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Wed Jun 30 15:04:31 2021. */

#ifndef PB_CRYPTOTRANSFERTRANSACTIONBODY_PB_H_INCLUDED
#define PB_CRYPTOTRANSFERTRANSACTIONBODY_PB_H_INCLUDED
#include <pb.h>

#include "BasicTypes.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HederaAccountAmount {
    HederaAccountID accountID;
    int64_t amount;
/* @@protoc_insertion_point(struct:HederaAccountAmount) */
} HederaAccountAmount;

typedef struct _HederaTransferList {
    pb_size_t accountAmounts_count;
    HederaAccountAmount accountAmounts[2];
/* @@protoc_insertion_point(struct:HederaTransferList) */
} HederaTransferList;

typedef struct _HederaCryptoTransferTransactionBody {
    HederaTransferList transfers;
/* @@protoc_insertion_point(struct:HederaCryptoTransferTransactionBody) */
} HederaCryptoTransferTransactionBody;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HederaAccountAmount_init_default         {HederaAccountID_init_default, 0}
#define HederaTransferList_init_default          {0, {HederaAccountAmount_init_default, HederaAccountAmount_init_default}}
#define HederaCryptoTransferTransactionBody_init_default {HederaTransferList_init_default}
#define HederaAccountAmount_init_zero            {HederaAccountID_init_zero, 0}
#define HederaTransferList_init_zero             {0, {HederaAccountAmount_init_zero, HederaAccountAmount_init_zero}}
#define HederaCryptoTransferTransactionBody_init_zero {HederaTransferList_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define HederaAccountAmount_accountID_tag        1
#define HederaAccountAmount_amount_tag           2
#define HederaTransferList_accountAmounts_tag    1
#define HederaCryptoTransferTransactionBody_transfers_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t HederaAccountAmount_fields[3];
extern const pb_field_t HederaTransferList_fields[2];
extern const pb_field_t HederaCryptoTransferTransactionBody_fields[2];

/* Maximum encoded size of messages (where known) */
#define HederaAccountAmount_size                 46
#define HederaTransferList_size                  96
#define HederaCryptoTransferTransactionBody_size 98

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CRYPTOTRANSFERTRANSACTIONBODY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
