/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Oct 22 17:59:12 2019. */

#include "CryptoCreateTransactionBody.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HederaCryptoCreateTransactionBody_fields[11] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, HederaCryptoCreateTransactionBody, key, key, &HederaKey_fields),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, initialBalance, key, 0),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, proxyAccountID, initialBalance, &HederaAccountID_fields),
    PB_FIELD(  6, UINT64  , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, sendRecordThreshold, proxyAccountID, 0),
    PB_FIELD(  7, UINT64  , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, receiveRecordThreshold, sendRecordThreshold, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, receiverSigRequired, receiveRecordThreshold, 0),
    PB_FIELD(  9, MESSAGE , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, autoRenewPeriod, receiverSigRequired, &HederaDuration_fields),
    PB_FIELD( 10, MESSAGE , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, shardID, autoRenewPeriod, &HederaShardID_fields),
    PB_FIELD( 11, MESSAGE , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, realmID, shardID, &HederaRealmID_fields),
    PB_FIELD( 12, MESSAGE , SINGULAR, STATIC  , OTHER, HederaCryptoCreateTransactionBody, newRealmAdminKey, realmID, &HederaKey_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(HederaCryptoCreateTransactionBody, key) < 65536 && pb_membersize(HederaCryptoCreateTransactionBody, proxyAccountID) < 65536 && pb_membersize(HederaCryptoCreateTransactionBody, autoRenewPeriod) < 65536 && pb_membersize(HederaCryptoCreateTransactionBody, shardID) < 65536 && pb_membersize(HederaCryptoCreateTransactionBody, realmID) < 65536 && pb_membersize(HederaCryptoCreateTransactionBody, newRealmAdminKey) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_HederaCryptoCreateTransactionBody)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(HederaCryptoCreateTransactionBody, key) < 256 && pb_membersize(HederaCryptoCreateTransactionBody, proxyAccountID) < 256 && pb_membersize(HederaCryptoCreateTransactionBody, autoRenewPeriod) < 256 && pb_membersize(HederaCryptoCreateTransactionBody, shardID) < 256 && pb_membersize(HederaCryptoCreateTransactionBody, realmID) < 256 && pb_membersize(HederaCryptoCreateTransactionBody, newRealmAdminKey) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_HederaCryptoCreateTransactionBody)
#endif


/* @@protoc_insertion_point(eof) */
