/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Jun 30 15:04:31 2021. */

#include "CryptoCreateTransactionBody.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HederaCryptoCreateTransactionBody_fields[2] = {
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , FIRST, HederaCryptoCreateTransactionBody, initialBalance, initialBalance, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
