/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "proto/CryptoTransferTransactionBody.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HederaAccountAmount, HederaAccountAmount, AUTO)


PB_BIND(HederaTransferList, HederaTransferList, AUTO)


PB_BIND(HederaCryptoTransferTransactionBody, HederaCryptoTransferTransactionBody, AUTO)



