/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Tue Oct 22 17:59:12 2019. */

#ifndef PB_CRYPTOCREATETRANSACTIONBODY_PB_H_INCLUDED
#define PB_CRYPTOCREATETRANSACTIONBODY_PB_H_INCLUDED
#include <pb.h>

#include "BasicTypes.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HederaCryptoCreateTransactionBody {
    HederaKey key;
    uint64_t initialBalance;
    HederaAccountID proxyAccountID;
    uint64_t sendRecordThreshold;
    uint64_t receiveRecordThreshold;
    bool receiverSigRequired;
    HederaDuration autoRenewPeriod;
    HederaShardID shardID;
    HederaRealmID realmID;
    HederaKey newRealmAdminKey;
/* @@protoc_insertion_point(struct:HederaCryptoCreateTransactionBody) */
} HederaCryptoCreateTransactionBody;

/* Default values for struct fields */

/* Initializer values for message structs */
#define HederaCryptoCreateTransactionBody_init_default {HederaKey_init_default, 0, HederaAccountID_init_default, 0, 0, 0, HederaDuration_init_default, HederaShardID_init_default, HederaRealmID_init_default, HederaKey_init_default}
#define HederaCryptoCreateTransactionBody_init_zero {HederaKey_init_zero, 0, HederaAccountID_init_zero, 0, 0, 0, HederaDuration_init_zero, HederaShardID_init_zero, HederaRealmID_init_zero, HederaKey_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define HederaCryptoCreateTransactionBody_key_tag 1
#define HederaCryptoCreateTransactionBody_initialBalance_tag 2
#define HederaCryptoCreateTransactionBody_proxyAccountID_tag 3
#define HederaCryptoCreateTransactionBody_sendRecordThreshold_tag 6
#define HederaCryptoCreateTransactionBody_receiveRecordThreshold_tag 7
#define HederaCryptoCreateTransactionBody_receiverSigRequired_tag 8
#define HederaCryptoCreateTransactionBody_autoRenewPeriod_tag 9
#define HederaCryptoCreateTransactionBody_shardID_tag 10
#define HederaCryptoCreateTransactionBody_realmID_tag 11
#define HederaCryptoCreateTransactionBody_newRealmAdminKey_tag 12

/* Struct field encoding specification for nanopb */
extern const pb_field_t HederaCryptoCreateTransactionBody_fields[11];

/* Maximum encoded size of messages (where known) */
#define HederaCryptoCreateTransactionBody_size   192

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CRYPTOCREATETRANSACTIONBODY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
