# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/crypto_transfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
from proto import basic_types_pb2 as proto_dot_basic__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/crypto_transfer.proto',
  package='Hedera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bproto/crypto_transfer.proto\x12\x06Hedera\x1a\x0cnanopb.proto\x1a\x17proto/basic_types.proto\"\x82\x01\n\x1d\x43ryptoTransferTransactionBody\x12\'\n\ttransfers\x18\x01 \x01(\x0b\x32\x14.Hedera.TransferList\x12\x38\n\x0etokenTransfers\x18\x02 \x03(\x0b\x32\x19.Hedera.TokenTransferListB\x05\x92?\x02\x10\x01\x62\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,proto_dot_basic__types__pb2.DESCRIPTOR,])




_CRYPTOTRANSFERTRANSACTIONBODY = _descriptor.Descriptor(
  name='CryptoTransferTransactionBody',
  full_name='Hedera.CryptoTransferTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transfers', full_name='Hedera.CryptoTransferTransactionBody.transfers', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenTransfers', full_name='Hedera.CryptoTransferTransactionBody.tokenTransfers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=209,
)

_CRYPTOTRANSFERTRANSACTIONBODY.fields_by_name['transfers'].message_type = proto_dot_basic__types__pb2._TRANSFERLIST
_CRYPTOTRANSFERTRANSACTIONBODY.fields_by_name['tokenTransfers'].message_type = proto_dot_basic__types__pb2._TOKENTRANSFERLIST
DESCRIPTOR.message_types_by_name['CryptoTransferTransactionBody'] = _CRYPTOTRANSFERTRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CryptoTransferTransactionBody = _reflection.GeneratedProtocolMessageType('CryptoTransferTransactionBody', (_message.Message,), dict(
  DESCRIPTOR = _CRYPTOTRANSFERTRANSACTIONBODY,
  __module__ = 'proto.crypto_transfer_pb2'
  # @@protoc_insertion_point(class_scope:Hedera.CryptoTransferTransactionBody)
  ))
_sym_db.RegisterMessage(CryptoTransferTransactionBody)


_CRYPTOTRANSFERTRANSACTIONBODY.fields_by_name['tokenTransfers']._options = None
# @@protoc_insertion_point(module_scope)
