"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Timestamp(google.protobuf.message.Message):
    """*
    An exact date and time. This is the same data structure as the protobuf
    Timestamp.proto (see the comments in
    https://github.com/google/protobuf
    /blob/master/src/google/protobuf/timestamp.proto)
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    """*
    Number of complete seconds since the start of the epoch
    """
    nanos: builtins.int
    """*
    Number of nanoseconds since the start of the last second
    """
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["nanos", b"nanos", "seconds", b"seconds"]) -> None: ...

global___Timestamp = Timestamp

@typing_extensions.final
class TimestampSeconds(google.protobuf.message.Message):
    """*
    An exact date and time,  with a resolution of one second (no nanoseconds).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    """*
    Number of complete seconds since the start of the epoch
    """
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["seconds", b"seconds"]) -> None: ...

global___TimestampSeconds = TimestampSeconds
