# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/TokenBurn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Wrappers_pb2 as proto_dot_Wrappers__pb2
from proto import BasicTypes_pb2 as proto_dot_BasicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/TokenBurn.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15proto/TokenBurn.proto\x1a\x14proto/Wrappers.proto\x1a\x16proto/BasicTypes.proto\"x\n\x1eHederaTokenBurnTransactionBody\x12\x1d\n\x05token\x18\x01 \x01(\x0b\x32\x0e.HederaTokenID\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x12\'\n\x11\x65xpected_decimals\x18\x04 \x01(\x0b\x32\x0c.UInt32Valueb\x06proto3')
  ,
  dependencies=[proto_dot_Wrappers__pb2.DESCRIPTOR,proto_dot_BasicTypes__pb2.DESCRIPTOR,])




_HEDERATOKENBURNTRANSACTIONBODY = _descriptor.Descriptor(
  name='HederaTokenBurnTransactionBody',
  full_name='HederaTokenBurnTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='HederaTokenBurnTransactionBody.token', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='HederaTokenBurnTransactionBody.amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expected_decimals', full_name='HederaTokenBurnTransactionBody.expected_decimals', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=191,
)

_HEDERATOKENBURNTRANSACTIONBODY.fields_by_name['token'].message_type = proto_dot_BasicTypes__pb2._HEDERATOKENID
_HEDERATOKENBURNTRANSACTIONBODY.fields_by_name['expected_decimals'].message_type = proto_dot_Wrappers__pb2._UINT32VALUE
DESCRIPTOR.message_types_by_name['HederaTokenBurnTransactionBody'] = _HEDERATOKENBURNTRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HederaTokenBurnTransactionBody = _reflection.GeneratedProtocolMessageType('HederaTokenBurnTransactionBody', (_message.Message,), dict(
  DESCRIPTOR = _HEDERATOKENBURNTRANSACTIONBODY,
  __module__ = 'proto.TokenBurn_pb2'
  # @@protoc_insertion_point(class_scope:HederaTokenBurnTransactionBody)
  ))
_sym_db.RegisterMessage(HederaTokenBurnTransactionBody)


# @@protoc_insertion_point(module_scope)
