"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import proto.basic_types_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TokenDissociateTransactionBody(google.protobuf.message.Message):
    """*
    Dissociates the provided account with the provided tokens. Must be signed by
    the provided Account's key. If the provided account is not found, the
    transaction will resolve to INVALID_ACCOUNT_ID. If the provided account has
    been deleted, the transaction will resolve to ACCOUNT_DELETED. If any of the
    provided tokens is not found, the transaction will resolve to
    INVALID_TOKEN_REF. If any of the provided tokens has been deleted, the
    transaction will resolve to TOKEN_WAS_DELETED. If an association between the
    provided account and any of the tokens does not exist, the transaction will
    resolve to TOKEN_NOT_ASSOCIATED_TO_ACCOUNT. If a token has not been deleted
    and has not expired, and the user has a nonzero balance, the transaction will
    resolve to TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES. If a <b>fungible
    token</b> has expired, the user can disassociate even if their token balance
    is not zero. If a <b>non fungible token</b> has expired, the user can
    <b>not</b> disassociate if their token balance is not zero. The transaction
    will resolve to TRANSACTION_REQUIRED_ZERO_TOKEN_BALANCES. On success,
    associations between the provided account and tokens are removed.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    TOKENS_FIELD_NUMBER: builtins.int
    @property
    def account(self) -> proto.basic_types_pb2.AccountID:
        """*
        The account to be dissociated with the provided tokens
        """
    @property
    def tokens(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[proto.basic_types_pb2.TokenID]:
        """*
        The tokens to be dissociated with the provided account
        Limited to 1 here
        """
    def __init__(
        self,
        *,
        account: proto.basic_types_pb2.AccountID | None = ...,
        tokens: collections.abc.Iterable[proto.basic_types_pb2.TokenID] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account", b"account"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account", b"account", "tokens", b"tokens"]) -> None: ...

global___TokenDissociateTransactionBody = TokenDissociateTransactionBody
