# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/TokenAssociate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
from proto import BasicTypes_pb2 as proto_dot_BasicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/TokenAssociate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1aproto/TokenAssociate.proto\x1a\x0cnanopb.proto\x1a\x16proto/BasicTypes.proto\"o\n#HederaTokenAssociateTransactionBody\x12!\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x10.HederaAccountID\x12%\n\x06tokens\x18\x02 \x03(\x0b\x32\x0e.HederaTokenIDB\x05\x92?\x02\x10\x01\x62\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,proto_dot_BasicTypes__pb2.DESCRIPTOR,])




_HEDERATOKENASSOCIATETRANSACTIONBODY = _descriptor.Descriptor(
  name='HederaTokenAssociateTransactionBody',
  full_name='HederaTokenAssociateTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='HederaTokenAssociateTransactionBody.account', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='HederaTokenAssociateTransactionBody.tokens', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=179,
)

_HEDERATOKENASSOCIATETRANSACTIONBODY.fields_by_name['account'].message_type = proto_dot_BasicTypes__pb2._HEDERAACCOUNTID
_HEDERATOKENASSOCIATETRANSACTIONBODY.fields_by_name['tokens'].message_type = proto_dot_BasicTypes__pb2._HEDERATOKENID
DESCRIPTOR.message_types_by_name['HederaTokenAssociateTransactionBody'] = _HEDERATOKENASSOCIATETRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HederaTokenAssociateTransactionBody = _reflection.GeneratedProtocolMessageType('HederaTokenAssociateTransactionBody', (_message.Message,), dict(
  DESCRIPTOR = _HEDERATOKENASSOCIATETRANSACTIONBODY,
  __module__ = 'proto.TokenAssociate_pb2'
  # @@protoc_insertion_point(class_scope:HederaTokenAssociateTransactionBody)
  ))
_sym_db.RegisterMessage(HederaTokenAssociateTransactionBody)


_HEDERATOKENASSOCIATETRANSACTIONBODY.fields_by_name['tokens']._options = None
# @@protoc_insertion_point(module_scope)
