# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/token_associate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
from proto import basic_types_pb2 as proto_dot_basic__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/token_associate.proto',
  package='Hedera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bproto/token_associate.proto\x12\x06Hedera\x1a\x0cnanopb.proto\x1a\x17proto/basic_types.proto\"k\n\x1dTokenAssociateTransactionBody\x12\"\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x11.Hedera.AccountID\x12&\n\x06tokens\x18\x02 \x03(\x0b\x32\x0f.Hedera.TokenIDB\x05\x92?\x02\x10\x01\x62\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,proto_dot_basic__types__pb2.DESCRIPTOR,])




_TOKENASSOCIATETRANSACTIONBODY = _descriptor.Descriptor(
  name='TokenAssociateTransactionBody',
  full_name='Hedera.TokenAssociateTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='Hedera.TokenAssociateTransactionBody.account', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='Hedera.TokenAssociateTransactionBody.tokens', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=185,
)

_TOKENASSOCIATETRANSACTIONBODY.fields_by_name['account'].message_type = proto_dot_basic__types__pb2._ACCOUNTID
_TOKENASSOCIATETRANSACTIONBODY.fields_by_name['tokens'].message_type = proto_dot_basic__types__pb2._TOKENID
DESCRIPTOR.message_types_by_name['TokenAssociateTransactionBody'] = _TOKENASSOCIATETRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenAssociateTransactionBody = _reflection.GeneratedProtocolMessageType('TokenAssociateTransactionBody', (_message.Message,), dict(
  DESCRIPTOR = _TOKENASSOCIATETRANSACTIONBODY,
  __module__ = 'proto.token_associate_pb2'
  # @@protoc_insertion_point(class_scope:Hedera.TokenAssociateTransactionBody)
  ))
_sym_db.RegisterMessage(TokenAssociateTransactionBody)


_TOKENASSOCIATETRANSACTIONBODY.fields_by_name['tokens']._options = None
# @@protoc_insertion_point(module_scope)
