# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/TransactionBody.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
from proto import BasicTypes_pb2 as proto_dot_BasicTypes__pb2
from proto import CryptoCreate_pb2 as proto_dot_CryptoCreate__pb2
from proto import Transfer_pb2 as proto_dot_Transfer__pb2
from proto import TokenAssociate_pb2 as proto_dot_TokenAssociate__pb2
from proto import TokenMint_pb2 as proto_dot_TokenMint__pb2
from proto import TokenBurn_pb2 as proto_dot_TokenBurn__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/TransactionBody.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bproto/TransactionBody.proto\x1a\x0cnanopb.proto\x1a\x16proto/BasicTypes.proto\x1a\x18proto/CryptoCreate.proto\x1a\x14proto/Transfer.proto\x1a\x1aproto/TokenAssociate.proto\x1a\x15proto/TokenMint.proto\x1a\x15proto/TokenBurn.proto\"\xa8\x03\n\x15HederaTransactionBody\x12+\n\rtransactionID\x18\x01 \x01(\x0b\x32\x14.HederaTransactionID\x12\x16\n\x0etransactionFee\x18\x03 \x01(\x04\x12\x13\n\x04memo\x18\x06 \x01(\tB\x05\x92?\x02\x08\x64\x12\x41\n\x13\x63ryptoCreateAccount\x18\x0b \x01(\x0b\x32\".HederaCryptoCreateTransactionBodyH\x00\x12>\n\x0e\x63ryptoTransfer\x18\x0e \x01(\x0b\x32$.HederaCryptoTransferTransactionBodyH\x00\x12>\n\x0etokenAssociate\x18( \x01(\x0b\x32$.HederaTokenAssociateTransactionBodyH\x00\x12\x34\n\ttokenMint\x18% \x01(\x0b\x32\x1f.HederaTokenMintTransactionBodyH\x00\x12\x34\n\ttokenBurn\x18& \x01(\x0b\x32\x1f.HederaTokenBurnTransactionBodyH\x00\x42\x06\n\x04\x64\x61tab\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,proto_dot_BasicTypes__pb2.DESCRIPTOR,proto_dot_CryptoCreate__pb2.DESCRIPTOR,proto_dot_Transfer__pb2.DESCRIPTOR,proto_dot_TokenAssociate__pb2.DESCRIPTOR,proto_dot_TokenMint__pb2.DESCRIPTOR,proto_dot_TokenBurn__pb2.DESCRIPTOR,])




_HEDERATRANSACTIONBODY = _descriptor.Descriptor(
  name='HederaTransactionBody',
  full_name='HederaTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='HederaTransactionBody.transactionID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactionFee', full_name='HederaTransactionBody.transactionFee', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='HederaTransactionBody.memo', index=2,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\010d'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cryptoCreateAccount', full_name='HederaTransactionBody.cryptoCreateAccount', index=3,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cryptoTransfer', full_name='HederaTransactionBody.cryptoTransfer', index=4,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenAssociate', full_name='HederaTransactionBody.tokenAssociate', index=5,
      number=40, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenMint', full_name='HederaTransactionBody.tokenMint', index=6,
      number=37, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenBurn', full_name='HederaTransactionBody.tokenBurn', index=7,
      number=38, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='HederaTransactionBody.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=192,
  serialized_end=616,
)

_HEDERATRANSACTIONBODY.fields_by_name['transactionID'].message_type = proto_dot_BasicTypes__pb2._HEDERATRANSACTIONID
_HEDERATRANSACTIONBODY.fields_by_name['cryptoCreateAccount'].message_type = proto_dot_CryptoCreate__pb2._HEDERACRYPTOCREATETRANSACTIONBODY
_HEDERATRANSACTIONBODY.fields_by_name['cryptoTransfer'].message_type = proto_dot_Transfer__pb2._HEDERACRYPTOTRANSFERTRANSACTIONBODY
_HEDERATRANSACTIONBODY.fields_by_name['tokenAssociate'].message_type = proto_dot_TokenAssociate__pb2._HEDERATOKENASSOCIATETRANSACTIONBODY
_HEDERATRANSACTIONBODY.fields_by_name['tokenMint'].message_type = proto_dot_TokenMint__pb2._HEDERATOKENMINTTRANSACTIONBODY
_HEDERATRANSACTIONBODY.fields_by_name['tokenBurn'].message_type = proto_dot_TokenBurn__pb2._HEDERATOKENBURNTRANSACTIONBODY
_HEDERATRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _HEDERATRANSACTIONBODY.fields_by_name['cryptoCreateAccount'])
_HEDERATRANSACTIONBODY.fields_by_name['cryptoCreateAccount'].containing_oneof = _HEDERATRANSACTIONBODY.oneofs_by_name['data']
_HEDERATRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _HEDERATRANSACTIONBODY.fields_by_name['cryptoTransfer'])
_HEDERATRANSACTIONBODY.fields_by_name['cryptoTransfer'].containing_oneof = _HEDERATRANSACTIONBODY.oneofs_by_name['data']
_HEDERATRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _HEDERATRANSACTIONBODY.fields_by_name['tokenAssociate'])
_HEDERATRANSACTIONBODY.fields_by_name['tokenAssociate'].containing_oneof = _HEDERATRANSACTIONBODY.oneofs_by_name['data']
_HEDERATRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _HEDERATRANSACTIONBODY.fields_by_name['tokenMint'])
_HEDERATRANSACTIONBODY.fields_by_name['tokenMint'].containing_oneof = _HEDERATRANSACTIONBODY.oneofs_by_name['data']
_HEDERATRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _HEDERATRANSACTIONBODY.fields_by_name['tokenBurn'])
_HEDERATRANSACTIONBODY.fields_by_name['tokenBurn'].containing_oneof = _HEDERATRANSACTIONBODY.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['HederaTransactionBody'] = _HEDERATRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HederaTransactionBody = _reflection.GeneratedProtocolMessageType('HederaTransactionBody', (_message.Message,), dict(
  DESCRIPTOR = _HEDERATRANSACTIONBODY,
  __module__ = 'proto.TransactionBody_pb2'
  # @@protoc_insertion_point(class_scope:HederaTransactionBody)
  ))
_sym_db.RegisterMessage(HederaTransactionBody)


_HEDERATRANSACTIONBODY.fields_by_name['memo']._options = None
# @@protoc_insertion_point(module_scope)
