# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transaction_body.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
from proto import basic_types_pb2 as proto_dot_basic__types__pb2
from proto import crypto_create_pb2 as proto_dot_crypto__create__pb2
from proto import crypto_transfer_pb2 as proto_dot_crypto__transfer__pb2
from proto import crypto_update_pb2 as proto_dot_crypto__update__pb2
from proto import duration_pb2 as proto_dot_duration__pb2
from proto import token_associate_pb2 as proto_dot_token__associate__pb2
from proto import token_burn_pb2 as proto_dot_token__burn__pb2
from proto import token_dissociate_pb2 as proto_dot_token__dissociate__pb2
from proto import token_mint_pb2 as proto_dot_token__mint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/transaction_body.proto',
  package='Hedera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cproto/transaction_body.proto\x12\x06Hedera\x1a\x0cnanopb.proto\x1a\x17proto/basic_types.proto\x1a\x19proto/crypto_create.proto\x1a\x1bproto/crypto_transfer.proto\x1a\x19proto/crypto_update.proto\x1a\x14proto/duration.proto\x1a\x1bproto/token_associate.proto\x1a\x16proto/token_burn.proto\x1a\x1cproto/token_dissociate.proto\x1a\x16proto/token_mint.proto\"\xa9\x05\n\x0fTransactionBody\x12,\n\rtransactionID\x18\x01 \x01(\x0b\x32\x15.Hedera.TransactionID\x12(\n\rnodeAccountID\x18\x02 \x01(\x0b\x32\x11.Hedera.AccountID\x12\x16\n\x0etransactionFee\x18\x03 \x01(\x04\x12\x32\n\x18transactionValidDuration\x18\x04 \x01(\x0b\x32\x10.Hedera.Duration\x12\x1a\n\x0egenerateRecord\x18\x05 \x01(\x08\x42\x02\x18\x01\x12\x13\n\x04memo\x18\x06 \x01(\tB\x05\x92?\x02\x08\x64\x12\x42\n\x13\x63ryptoCreateAccount\x18\x0b \x01(\x0b\x32#.Hedera.CryptoCreateTransactionBodyH\x00\x12?\n\x0e\x63ryptoTransfer\x18\x0e \x01(\x0b\x32%.Hedera.CryptoTransferTransactionBodyH\x00\x12\x42\n\x13\x63ryptoUpdateAccount\x18\x0f \x01(\x0b\x32#.Hedera.CryptoUpdateTransactionBodyH\x00\x12\x35\n\ttokenMint\x18% \x01(\x0b\x32 .Hedera.TokenMintTransactionBodyH\x00\x12\x35\n\ttokenBurn\x18& \x01(\x0b\x32 .Hedera.TokenBurnTransactionBodyH\x00\x12?\n\x0etokenAssociate\x18( \x01(\x0b\x32%.Hedera.TokenAssociateTransactionBodyH\x00\x12\x41\n\x0ftokenDissociate\x18) \x01(\x0b\x32&.Hedera.TokenDissociateTransactionBodyH\x00\x42\x06\n\x04\x64\x61tab\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,proto_dot_basic__types__pb2.DESCRIPTOR,proto_dot_crypto__create__pb2.DESCRIPTOR,proto_dot_crypto__transfer__pb2.DESCRIPTOR,proto_dot_crypto__update__pb2.DESCRIPTOR,proto_dot_duration__pb2.DESCRIPTOR,proto_dot_token__associate__pb2.DESCRIPTOR,proto_dot_token__burn__pb2.DESCRIPTOR,proto_dot_token__dissociate__pb2.DESCRIPTOR,proto_dot_token__mint__pb2.DESCRIPTOR,])




_TRANSACTIONBODY = _descriptor.Descriptor(
  name='TransactionBody',
  full_name='Hedera.TransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='Hedera.TransactionBody.transactionID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeAccountID', full_name='Hedera.TransactionBody.nodeAccountID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactionFee', full_name='Hedera.TransactionBody.transactionFee', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactionValidDuration', full_name='Hedera.TransactionBody.transactionValidDuration', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generateRecord', full_name='Hedera.TransactionBody.generateRecord', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='Hedera.TransactionBody.memo', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\010d'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cryptoCreateAccount', full_name='Hedera.TransactionBody.cryptoCreateAccount', index=6,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cryptoTransfer', full_name='Hedera.TransactionBody.cryptoTransfer', index=7,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cryptoUpdateAccount', full_name='Hedera.TransactionBody.cryptoUpdateAccount', index=8,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenMint', full_name='Hedera.TransactionBody.tokenMint', index=9,
      number=37, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenBurn', full_name='Hedera.TransactionBody.tokenBurn', index=10,
      number=38, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenAssociate', full_name='Hedera.TransactionBody.tokenAssociate', index=11,
      number=40, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenDissociate', full_name='Hedera.TransactionBody.tokenDissociate', index=12,
      number=41, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='Hedera.TransactionBody.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=292,
  serialized_end=973,
)

_TRANSACTIONBODY.fields_by_name['transactionID'].message_type = proto_dot_basic__types__pb2._TRANSACTIONID
_TRANSACTIONBODY.fields_by_name['nodeAccountID'].message_type = proto_dot_basic__types__pb2._ACCOUNTID
_TRANSACTIONBODY.fields_by_name['transactionValidDuration'].message_type = proto_dot_duration__pb2._DURATION
_TRANSACTIONBODY.fields_by_name['cryptoCreateAccount'].message_type = proto_dot_crypto__create__pb2._CRYPTOCREATETRANSACTIONBODY
_TRANSACTIONBODY.fields_by_name['cryptoTransfer'].message_type = proto_dot_crypto__transfer__pb2._CRYPTOTRANSFERTRANSACTIONBODY
_TRANSACTIONBODY.fields_by_name['cryptoUpdateAccount'].message_type = proto_dot_crypto__update__pb2._CRYPTOUPDATETRANSACTIONBODY
_TRANSACTIONBODY.fields_by_name['tokenMint'].message_type = proto_dot_token__mint__pb2._TOKENMINTTRANSACTIONBODY
_TRANSACTIONBODY.fields_by_name['tokenBurn'].message_type = proto_dot_token__burn__pb2._TOKENBURNTRANSACTIONBODY
_TRANSACTIONBODY.fields_by_name['tokenAssociate'].message_type = proto_dot_token__associate__pb2._TOKENASSOCIATETRANSACTIONBODY
_TRANSACTIONBODY.fields_by_name['tokenDissociate'].message_type = proto_dot_token__dissociate__pb2._TOKENDISSOCIATETRANSACTIONBODY
_TRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _TRANSACTIONBODY.fields_by_name['cryptoCreateAccount'])
_TRANSACTIONBODY.fields_by_name['cryptoCreateAccount'].containing_oneof = _TRANSACTIONBODY.oneofs_by_name['data']
_TRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _TRANSACTIONBODY.fields_by_name['cryptoTransfer'])
_TRANSACTIONBODY.fields_by_name['cryptoTransfer'].containing_oneof = _TRANSACTIONBODY.oneofs_by_name['data']
_TRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _TRANSACTIONBODY.fields_by_name['cryptoUpdateAccount'])
_TRANSACTIONBODY.fields_by_name['cryptoUpdateAccount'].containing_oneof = _TRANSACTIONBODY.oneofs_by_name['data']
_TRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _TRANSACTIONBODY.fields_by_name['tokenMint'])
_TRANSACTIONBODY.fields_by_name['tokenMint'].containing_oneof = _TRANSACTIONBODY.oneofs_by_name['data']
_TRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _TRANSACTIONBODY.fields_by_name['tokenBurn'])
_TRANSACTIONBODY.fields_by_name['tokenBurn'].containing_oneof = _TRANSACTIONBODY.oneofs_by_name['data']
_TRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _TRANSACTIONBODY.fields_by_name['tokenAssociate'])
_TRANSACTIONBODY.fields_by_name['tokenAssociate'].containing_oneof = _TRANSACTIONBODY.oneofs_by_name['data']
_TRANSACTIONBODY.oneofs_by_name['data'].fields.append(
  _TRANSACTIONBODY.fields_by_name['tokenDissociate'])
_TRANSACTIONBODY.fields_by_name['tokenDissociate'].containing_oneof = _TRANSACTIONBODY.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['TransactionBody'] = _TRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionBody = _reflection.GeneratedProtocolMessageType('TransactionBody', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONBODY,
  __module__ = 'proto.transaction_body_pb2'
  # @@protoc_insertion_point(class_scope:Hedera.TransactionBody)
  ))
_sym_db.RegisterMessage(TransactionBody)


_TRANSACTIONBODY.fields_by_name['generateRecord']._options = None
_TRANSACTIONBODY.fields_by_name['memo']._options = None
# @@protoc_insertion_point(module_scope)
