/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PROTO_TRANSACTIONBODY_PB_H_INCLUDED
#define PB_PROTO_TRANSACTIONBODY_PB_H_INCLUDED
#include <pb.h>
#include "proto/BasicTypes.pb.h"
#include "proto/CryptoCreateTransactionBody.pb.h"
#include "proto/CryptoTransferTransactionBody.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _HederaTransactionBody { 
    bool has_transactionID;
    HederaTransactionID transactionID; 
    uint64_t transactionFee; 
    char memo[100]; 
    pb_size_t which_data;
    union {
        HederaCryptoCreateTransactionBody cryptoCreateAccount;
        HederaCryptoTransferTransactionBody cryptoTransfer;
    } data; 
} HederaTransactionBody;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HederaTransactionBody_init_default       {false, HederaTransactionID_init_default, 0, "", 0, {HederaCryptoCreateTransactionBody_init_default}}
#define HederaTransactionBody_init_zero          {false, HederaTransactionID_init_zero, 0, "", 0, {HederaCryptoCreateTransactionBody_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define HederaTransactionBody_transactionID_tag  1
#define HederaTransactionBody_transactionFee_tag 3
#define HederaTransactionBody_memo_tag           6
#define HederaTransactionBody_cryptoCreateAccount_tag 11
#define HederaTransactionBody_cryptoTransfer_tag 14

/* Struct field encoding specification for nanopb */
#define HederaTransactionBody_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transactionID,     1) \
X(a, STATIC,   SINGULAR, UINT64,   transactionFee,    3) \
X(a, STATIC,   SINGULAR, STRING,   memo,              6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,cryptoCreateAccount,data.cryptoCreateAccount),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,cryptoTransfer,data.cryptoTransfer),  14)
#define HederaTransactionBody_CALLBACK NULL
#define HederaTransactionBody_DEFAULT NULL
#define HederaTransactionBody_transactionID_MSGTYPE HederaTransactionID
#define HederaTransactionBody_data_cryptoCreateAccount_MSGTYPE HederaCryptoCreateTransactionBody
#define HederaTransactionBody_data_cryptoTransfer_MSGTYPE HederaCryptoTransferTransactionBody

extern const pb_msgdesc_t HederaTransactionBody_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HederaTransactionBody_fields &HederaTransactionBody_msg

/* Maximum encoded size of messages (where known) */
#define HederaTransactionBody_size               249

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
