# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Wrappers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/Wrappers.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14proto/Wrappers.proto\"\x1c\n\x0bUInt32Value\x12\r\n\x05value\x18\x01 \x01(\rb\x06proto3')
)




_UINT32VALUE = _descriptor.Descriptor(
  name='UInt32Value',
  full_name='UInt32Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='UInt32Value.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['UInt32Value'] = _UINT32VALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UInt32Value = _reflection.GeneratedProtocolMessageType('UInt32Value', (_message.Message,), dict(
  DESCRIPTOR = _UINT32VALUE,
  __module__ = 'proto.Wrappers_pb2'
  # @@protoc_insertion_point(class_scope:UInt32Value)
  ))
_sym_db.RegisterMessage(UInt32Value)


# @@protoc_insertion_point(module_scope)
